### ISSUE TITLE
minimal example doesn't work

### ISSUE THREAD

**Issue by TvrtkoM** [vertical-knowledge/flask-ripozo#3]
Imports doesn't match the current ripozo module state (see commit below). If this is corrected however I get:

```
    super(FlaskDispatcher, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'base_url'
```

while executing _dispatcher = FlaskDispatcher(app, base_url='/api')_ pointing to line 101 in dispacher.py

**Comment by TvrtkoM** [comment]
see the change in README here: 6c4268e1e628903db9fe53ab5df91ab6aea9cdd0

**Comment by TvrtkoM** [comment]
I've managed to run example with the changes in README in the pull request.

**Comment by timmartin19** [comment]
Thank you!  I'll try to add doctests sometime soon to ensure this doesn't happen again.
